import type { DisplayConfig, FrameAnimation } from '../types';
import { toCId, computeAnimBoundingBox } from './helpers';
import { emitAnimPROGMEM, emitAnimPlaybackFn } from './emitScreen';

export interface AnimSnippetOptions {
  display: DisplayConfig;
  animations: FrameAnimation[];
}

/**
 * Generate a self-contained C++ snippet for one or more animations.
 *
 * Each animation is emitted with a position-parameterised playback function:
 *   void drawAnim_<name>(int16_t px, int16_t py)
 *
 * The snippet is designed to be pasted directly into an existing Arduino sketch
 * after the u8g2 display object declaration.  No setup()/loop() boilerplate is
 * included — just the PROGMEM data and the draw functions.
 *
 * The bounding box of each animation is automatically cropped so only the
 * pixels that actually change are stored in flash (Phase-1 optimisation).
 * XOR-delta encoding further reduces per-frame storage (Phase-2 optimisation).
 */
export function generateAnimSnippet(opts: AnimSnippetOptions): string {
  const { display, animations } = opts;
  const visible = animations.filter(a => a.visible && a.frames.length > 0);

  const lines: string[] = [];

  lines.push('// =============================================================');
  lines.push('//  Animation Snippet — generated by OLED Canvas Studio');
  lines.push(`//  Display: ${display.type} ${display.width}x${display.height}`);
  lines.push('//');
  lines.push('//  USAGE');
  lines.push('//  -----');
  lines.push('//  1. Paste this snippet into your .ino / .cpp file, AFTER the');
  lines.push('//     u8g2 display object declaration.');
  lines.push('//  2. Inside your screen-drawing code call:');
  for (const a of visible) {
    const animId = toCId(a.id);
    lines.push(`//       drawAnim_${animId}(x, y);   // "${a.name}"`);
  }
  lines.push('//     where (x, y) is where you want the top-left of the');
  lines.push('//     animation bounding box to appear on screen.');
  lines.push('//  3. Call the function every loop iteration — it manages its');
  lines.push('//     own frame timing using millis().');
  lines.push('// =============================================================');
  lines.push('');
  lines.push('#include <Arduino.h>');
  lines.push('#include <U8g2lib.h>');
  lines.push('');
  lines.push('// Forward-declare the global display object defined in your sketch.');
  lines.push('extern U8G2& u8g2;  // <-- change type to match your display class if needed');
  lines.push('');

  if (visible.length === 0) {
    lines.push('// (no visible animations to export)');
    return lines.join('\n');
  }

  for (const a of visible) {
    const animId = toCId(a.id);
    const bbox_hint = (() => {
      // Quick bbox preview for the comment
      const b = computeBboxHint(a, display);
      return b ? `  bbox: ${b.w}×${b.h} px at (${b.x},${b.y}) on the original canvas` : '';
    })();

    lines.push(`// ------------------------------------------------------------`);
    lines.push(`//  "${a.name}"  (${a.frames.length} frame${a.frames.length === 1 ? '' : 's'}, ${a.playMode})${bbox_hint ? '\n// ' + bbox_hint : ''}`);
    lines.push(`// ------------------------------------------------------------`);

    const meta = emitAnimPROGMEM(lines, a, display, animId);
    // In a snippet the caller supplies the draw position via (px, py)
    emitAnimPlaybackFn(lines, meta, 'px', 'py', true);
    lines.push('');
  }

  return lines.join('\n');
}

/** Return a short bbox description used only for the comment header. */
function computeBboxHint(
  a: FrameAnimation,
  display: DisplayConfig,
): { x: number; y: number; w: number; h: number } | null {
  try {
    return computeAnimBoundingBox(a, display.width, display.height);
  } catch {
    return null;
  }
}

// Re-export so external callers don't need to import helpers separately
export type { AnimEmitMeta } from './emitScreen';
